#!/bin/bash

apt-get update && apt-get install -y curl unzip python python-pip
pip install -U pip tox

## Get latest rancher-catalog
download_url="http://192.168.1.101/devops/rancher-catalog/repository/archive.zip"
curl -sL -o /tmp/rancher-catalog-service.zip ${download_url}
unzip /tmp/rancher-catalog-service.zip -d /usr/bin/