# -*- mode: ruby -*-
# vi: set ft=ruby :
require "ipaddr"
base_ip="192.168.1.101"

Vagrant.configure("2") do |config|
  config.vm.network "forwarded_port", guest: 9100, host: 9103
  ip_address = IPAddr.new base_ip

	config.vm.provider "virtualbox" do |v|
	  v.memory = 512
	end
  ip_address = ip_address.succ
  config.vm.define "third_node" do |esno|
      esno.vm.box = "ubuntu/bionic64"
      esno.vm.network "private_network", ip: ip_address.to_s
      config.vm.provision "shell" do |s|
         s.inline = "cd /vagrant/agents/;./nodeExporterInstall.sh"
      end
   end
end
