# -*- mode: ruby -*-
# vi: set ft=ruby :
require "ipaddr"
base_ip="192.168.1.99"

Vagrant.configure("2") do |config|
  ip_address = IPAddr.new base_ip

	config.vm.provider "virtualbox" do |v|
	  v.memory = 2048
	end
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8443, host: 8443
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 9090, host: 9090
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  ip_address = ip_address.succ
  config.vm.define "rancher_vg" do |esno|
      esno.vm.box = "ubuntu/bionic64"
      esno.vm.network "private_network", ip: ip_address.to_s
      esno.vm.provision "docker" do |d|
        d.post_install_provision "shell", inline: "sudo cp /vagrant/daemon.json /etc/docker/;sudo service docker restart"
        d.run "rancher", image:"rancher/server",
          args: "-d --restart=unless-stopped -p 8080:8080 -p 8443:8443"
      end
   end
end
