# -*- mode: ruby -*-
# vi: set ft=ruby :
require "ipaddr"
base_ip="192.168.1.101"

Vagrant.configure("2") do |config|
  config.vm.network "forwarded_port", guest: 9102, host: 9102
  config.vm.network "forwarded_port", guest: 9100, host: 9100
  ip_address = IPAddr.new base_ip

	config.vm.provider "virtualbox" do |v|
	  v.memory = 1024
	end
  ip_address = ip_address.succ
  config.vm.define "rancher_vg" do |esno|
      esno.vm.box = "ubuntu/bionic64"
      esno.vm.network "private_network", ip: ip_address.to_s
      esno.vm.provision "docker" do |d|
        d.post_install_provision "shell", inline: "sudo cp /vagrant/daemon.json /etc/docker/;sudo service docker restart"
      end
   end
end
